GET http://192.168.1.128:8080/dersler/get
###

GET http://192.168.1.128:8080/dersler/getDerslerByDersKodu/BRT
###

POST http://192.168.1.128:8080/dersler/getDerslerByProgramlar
content-type: application/json

{
    "PROG_IDs": [715701, 716026]
}
###

POST http://192.168.1.128:8080/dersler/create
content-type: application/json

{
    "DERS_KODU": "BRT20714",
    "DERS_ADI_TR": "BERAT ALLAHVERDI",
    "DERS_ADI_EN": "ERTUGRUL BERAT ALLAHVERDI",
    "PROG_ID": 999999,
    "TU": 4,
    "KREDI": 0,
    "AKTS": 4,
    "YARIYIL": 1,
    "AKADEMIK_ID": 1,
    "AKTIF": 1
}
###
POST http://192.168.1.128/sorgu/Welcome
content-type: application/json

{
    "DERS_KODU": "BRT20714",
    "DERS_ADI_TR": "BERAT ALLAHVERDI",
    "DERS_ADI_EN": "ERTUGRUL BERAT ALLAHVERDI",
    "PROG_ID": 999999,
    "TU": 4,
    "KREDI": 0,
    "AKTS": 4,
    "YARIYIL": 1,
    "AKADEMIK_ID": 1,
    "AKTIF": 1
}
###
PUT http://192.168.1.128:8080/dersler/update
content-type: application/json

{
    "DERS_KODU": "BRT20714",
    "DERS_ADI_TR": "ERTUGRUL BERAT",
    "DERS_ADI_EN": "ALLAHVERDI",
    "PROG_ID": 999999,
    "TU": 4,
    "KREDI": 0,
    "AKTS": 4,
    "YARIYIL": 1,
    "AKADEMIK_ID": 1,
    "AKTIF": 1
}

###
DELETE  http://192.168.1.128:8080/dersler/delete
content-type: application/json

{
    "DERS_KODU": "BRT20714",
    "PROG_ID": 999999
}

###